### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by ivcreative** [kellymears/tailwind-gutenberg-components#10]
Is this no longer been develop or maintained?

please let us know so we can try to contribute like documentation is missing for this.

**Comment by kellymears** [comment]
I don't think there are any PRs open on this so:

- It is being maintained (by me)
- It is not being developed (by everyone)

I got kinda burned out on this, partly due to lack of contributions, but I'm still around and maybe in the future I will revisit it. In the meantime if you have bugfixes, improvements, docs, etc. feel free to issue a PR. If it's a big sweeping change, create an issue first and see how other people feel about it.
